### ISSUE TITLE
Submissions should be made with a copy of SUBMISSIONS.Rmd

### ISSUE THREAD

**Issue by cforgaci** [Rbanism/logo#2]
We noticed an issue with the submission procedure. To keep all submissions, we need to ask contributors to make a copy of `SUBMISSION.Rmd` and rename it to `SUBMISSION-FirstnameSurname.Rmd`. That way, we can collect all submissions and avoid conflicts, when PRs starts coming in on the same file.

Ideally, this would have been done with an issue template like in the scalegis-challenge or repro-challenge, but making a copy is a good workaround and does not require big changes in the submission tutorial. @DimitrisMantas, what is the easiest way to specify this in the guidelines and video?

**Comment by DimitrisMantas** [comment]
I don't see a problem since only one submission will be merged in the end. However, I understand that having copies of the submission template helps with organization.

I can ammend the guidelines, but the video cannot be changed without the relevant parts needing to be reshot and recut, unfortunately.

**Comment by cforgaci** [comment]
@DimitrisMantas, thanks for your answer. See my suggestions below:

> I don't see a problem since only one submission will be merged in the end. However, I understand that having copies of the submission template helps with organization.

The thing is that we will most likely end up with a mix of solutions in the end that we compile from multiple submissions, not simply selecting a "winner". In this sense, this is just an early stage of the collaborative development process in which we simply gather ideas and we reorganise the content into an actual open-source repo in which we co-develop the logo generator afterwards.

> I can ammend the guidelines, but the video cannot be changed without the relevant parts needing to be reshot and recut, unfortunately.

No need to reshoot, cut etc. Can we simply add the requirement in `SUBMISSION.Rmd` that the file should be duplicated and renamed, highlighted as an **UPDATE**? See the naming convention I suggested in my first comment in this issue. That should solve the problem.

**Comment by DimitrisMantas** [comment]
Implemented in https://github.com/Rbanism/logo/commit/9adf66804e6849fae16a923b72cff0c6da59ac06.
